# Generated by Django 4.1.4 on 2022-12-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
