# Generated by Django 4.1.4 on 2022-12-23 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_school_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
